export type USBankInfo = {
  name: string;
  fullName: string;
  type: string;
  headquarters: string;
  founded: string;
  customers: string;
  color: string;
  statementFormats: string[];
  popularFor: string[];
  downloadInstructions: { title: string; steps: string[] }[];
};

export const usBanks: Record<string, USBankInfo> = {
  "chase-bank": {
    name: "Chase",
    fullName: "JPMorgan Chase Bank, N.A.",
    type: "National Bank",
    headquarters: "New York, NY",
    founded: "1799",
    customers: "80 million+",
    color: "#117ACA",
    statementFormats: ["Chase Online PDF", "Chase Mobile App PDF", "Paper Statement PDF", "Business Account Statement"],
    popularFor: ["Chase Total Checking statements", "Chase Sapphire credit card PDF", "Business banking exports for QuickBooks"],
    downloadInstructions: [
      { title: "Chase Online Banking", steps: ["Log in at chase.com", "Go to Accounts → select account", "Click Statements & Documents", "Choose date range and Download PDF"] },
      { title: "Chase Mobile App", steps: ["Open Chase Mobile app", "Tap the account", "Select Statements", "Tap the statement to download PDF"] },
    ],
  },
  "bank-of-america": {
    name: "Bank of America",
    fullName: "Bank of America, N.A.",
    type: "National Bank",
    headquarters: "Charlotte, NC",
    founded: "1904",
    customers: "68 million+",
    color: "#E31837",
    statementFormats: ["Bank of America Online PDF", "Mobile Banking PDF", "Merrill Lynch Statement", "Small Business Statement"],
    popularFor: ["Checking & savings PDF export", "Merrill investment statements", "QuickBooks & Xero import"],
    downloadInstructions: [
      { title: "Online Banking", steps: ["Sign in at bankofamerica.com", "Select your account", "Click Statements & Documents", "Download the PDF for your date range"] },
      { title: "Mobile App", steps: ["Open Bank of America app", "Tap account", "Tap View Statements", "Select and download PDF"] },
    ],
  },
  "wells-fargo": {
    name: "Wells Fargo",
    fullName: "Wells Fargo Bank, N.A.",
    type: "National Bank",
    headquarters: "San Francisco, CA",
    founded: "1852",
    customers: "70 million+",
    color: "#CD1409",
    statementFormats: ["Wells Fargo Online PDF", "Mobile App Statement", "Business Banking Statement", "Advisor Statement"],
    popularFor: ["Everyday Checking PDF", "Business account for bookkeeping", "Tax document export"],
    downloadInstructions: [
      { title: "Online Banking", steps: ["Sign in at wellsfargo.com", "Go to Account Activity", "Click Statements", "Select date and Download PDF"] },
      { title: "Wells Fargo Mobile", steps: ["Open the Wells Fargo app", "Select account", "Tap Statements", "Download PDF"] },
    ],
  },
  "citibank": {
    name: "Citibank",
    fullName: "Citibank, N.A.",
    type: "National Bank",
    headquarters: "New York, NY",
    founded: "1812",
    customers: "200 million+ globally",
    color: "#003B8E",
    statementFormats: ["Citi Online PDF", "Citi Mobile PDF", "Citi Business Statement", "Citi Credit Card Statement"],
    popularFor: ["Citi Double Cash card PDF", "International account statements", "Business expense tracking"],
    downloadInstructions: [
      { title: "Citi Online", steps: ["Log in at citibank.com", "Select your account", "Click Statements", "Choose period and Download PDF"] },
      { title: "Citi Mobile App", steps: ["Open Citi Mobile app", "Tap your account", "Select Statements", "Download the PDF"] },
    ],
  },
  "us-bank": {
    name: "U.S. Bank",
    fullName: "U.S. Bancorp",
    type: "National Bank",
    headquarters: "Minneapolis, MN",
    founded: "1863",
    customers: "19 million+",
    color: "#0A2B7D",
    statementFormats: ["U.S. Bank Online PDF", "Mobile App Statement", "Business Checking Statement", "ReliaCard Statement"],
    popularFor: ["Business banking exports", "USB Altitude card PDF", "Payroll account statements"],
    downloadInstructions: [
      { title: "Online Banking", steps: ["Log in at usbank.com", "Select account", "Click View Statements", "Download PDF"] },
      { title: "U.S. Bank Mobile", steps: ["Open U.S. Bank app", "Tap account", "Select Statements", "Download"] },
    ],
  },
  "truist-bank": {
    name: "Truist",
    fullName: "Truist Bank",
    type: "Regional Bank",
    headquarters: "Charlotte, NC",
    founded: "2019",
    customers: "15 million+",
    color: "#5C068C",
    statementFormats: ["Truist Online PDF", "Truist Mobile PDF", "Business Statement", "Investment Statement"],
    popularFor: ["Truist One checking PDF", "Mortgage statements", "Small business bookkeeping"],
    downloadInstructions: [
      { title: "Truist Online Banking", steps: ["Log in at truist.com", "Select account", "Click Statements", "Download PDF"] },
      { title: "Truist Mobile App", steps: ["Open Truist app", "Tap account", "Select Statements & Docs", "Download PDF"] },
    ],
  },
  "pnc-bank": {
    name: "PNC Bank",
    fullName: "PNC Financial Services Group",
    type: "Regional Bank",
    headquarters: "Pittsburgh, PA",
    founded: "1852",
    customers: "12 million+",
    color: "#F15A22",
    statementFormats: ["PNC Online PDF", "Virtual Wallet Statement", "Business Checking Statement", "PNC Mobile PDF"],
    popularFor: ["Virtual Wallet budgeting exports", "Business account for accountants", "Tax-time statement download"],
    downloadInstructions: [
      { title: "PNC Online Banking", steps: ["Log in at pnc.com", "Select account", "Click Statements", "Download PDF"] },
      { title: "PNC Mobile App", steps: ["Open PNC app", "Tap account", "Select Statements", "Tap to download PDF"] },
    ],
  },
  "capital-one": {
    name: "Capital One",
    fullName: "Capital One Financial Corporation",
    type: "National Bank",
    headquarters: "McLean, VA",
    founded: "1994",
    customers: "100 million+ cards",
    color: "#D03027",
    statementFormats: ["Capital One Online PDF", "360 Checking Statement", "Venture Card Statement", "Business Card Statement"],
    popularFor: ["Venture & Quicksilver card PDFs", "360 Checking exports", "Business expense reconciliation"],
    downloadInstructions: [
      { title: "Capital One Online", steps: ["Log in at capitalone.com", "Select account", "Click View Statements", "Download PDF"] },
      { title: "Capital One Mobile", steps: ["Open Capital One app", "Tap account", "Select Statements", "Download PDF"] },
    ],
  },
  "td-bank": {
    name: "TD Bank",
    fullName: "TD Bank, N.A.",
    type: "Regional Bank",
    headquarters: "Cherry Hill, NJ",
    founded: "1852",
    customers: "10 million+ in US",
    color: "#34B233",
    statementFormats: ["TD Bank Online PDF", "Mobile App Statement", "Business Checking PDF", "TD Credit Card Statement"],
    popularFor: ["TD Convenience Checking PDF", "Business account exports", "Accounting software import"],
    downloadInstructions: [
      { title: "TD Online Banking", steps: ["Log in at tdbank.com", "Select account", "Click Statements", "Download PDF"] },
      { title: "TD Bank Mobile", steps: ["Open TD Bank app", "Tap account", "Select Statements", "Download"] },
    ],
  },
  "ally-bank": {
    name: "Ally Bank",
    fullName: "Ally Bank",
    type: "Online Bank",
    headquarters: "Sandy, UT",
    founded: "2009",
    customers: "11 million+",
    color: "#7C2281",
    statementFormats: ["Ally Online PDF", "High-Yield Savings Statement", "Ally Invest Statement", "CD Account Statement"],
    popularFor: ["High-yield savings exports", "Investment account CSV", "Auto loan statements"],
    downloadInstructions: [
      { title: "Ally Online Banking", steps: ["Log in at ally.com", "Select account", "Click Documents & Statements", "Download PDF"] },
      { title: "Ally Mobile App", steps: ["Open Ally app", "Tap account", "Select Statements", "Download PDF"] },
    ],
  },
  "charles-schwab": {
    name: "Charles Schwab",
    fullName: "Charles Schwab Bank, SSB",
    type: "Investment Bank",
    headquarters: "Westlake, TX",
    founded: "1971",
    customers: "34 million+",
    color: "#00A0DF",
    statementFormats: ["Schwab Online PDF", "Brokerage Statement", "Schwab Checking Statement", "IRA Statement"],
    popularFor: ["Brokerage account exports for taxes", "Checking PDF for QuickBooks", "IRA annual statements"],
    downloadInstructions: [
      { title: "Schwab.com", steps: ["Log in at schwab.com", "Select account", "Click Statements", "Download PDF"] },
      { title: "Schwab Mobile", steps: ["Open Schwab app", "Tap account", "Select Statements", "Download PDF"] },
    ],
  },
  "navy-federal": {
    name: "Navy Federal",
    fullName: "Navy Federal Credit Union",
    type: "Credit Union",
    headquarters: "Vienna, VA",
    founded: "1933",
    customers: "13 million+",
    color: "#003087",
    statementFormats: ["NFCU Online PDF", "Checking Statement", "NFCU Credit Card PDF", "Savings Statement"],
    popularFor: ["Military checking exports", "VA loan statements", "Member advantage checking PDF"],
    downloadInstructions: [
      { title: "Online Banking", steps: ["Log in at navyfederal.org", "Select account", "Click Statements & Documents", "Download PDF"] },
      { title: "NFCU Mobile", steps: ["Open Navy Federal app", "Tap account", "Select Statements", "Download PDF"] },
    ],
  },
  "citizens-bank": {
    name: "Citizens Bank",
    fullName: "Citizens Financial Group",
    type: "Regional Bank",
    headquarters: "Providence, RI",
    founded: "1828",
    customers: "7 million+",
    color: "#00517C",
    statementFormats: ["Citizens Online PDF", "Citizens Access Savings", "Business Checking PDF", "Student Account Statement"],
    popularFor: ["Student loan statements", "Business checking exports", "Citizens Access high-yield PDF"],
    downloadInstructions: [
      { title: "Citizens Online", steps: ["Log in at citizensbank.com", "Select account", "Click Statements", "Download PDF"] },
      { title: "Citizens Mobile", steps: ["Open Citizens app", "Tap account", "Select Statements", "Download"] },
    ],
  },
  "fifth-third-bank": {
    name: "Fifth Third Bank",
    fullName: "Fifth Third Bank, National Association",
    type: "Regional Bank",
    headquarters: "Cincinnati, OH",
    founded: "1858",
    customers: "5.5 million+",
    color: "#005A32",
    statementFormats: ["Fifth Third Online PDF", "Mobile Statement", "Business Checking PDF", "Momentum Checking Statement"],
    popularFor: ["Midwest business banking exports", "Momentum checking PDF", "Payroll account statements"],
    downloadInstructions: [
      { title: "53.com Online Banking", steps: ["Log in at 53.com", "Select account", "Click Statements", "Download PDF"] },
      { title: "Fifth Third Mobile", steps: ["Open Fifth Third app", "Tap account", "Tap Statements", "Download PDF"] },
    ],
  },
  "regions-bank": {
    name: "Regions Bank",
    fullName: "Regions Financial Corporation",
    type: "Regional Bank",
    headquarters: "Birmingham, AL",
    founded: "1971",
    customers: "7 million+",
    color: "#00703C",
    statementFormats: ["Regions Online PDF", "LifeGreen Checking Statement", "Business Checking PDF", "Regions Credit Card Statement"],
    popularFor: ["Southeast US banking exports", "LifeGreen checking PDF", "Business bookkeeping CSV"],
    downloadInstructions: [
      { title: "Regions Online", steps: ["Log in at regions.com", "Select account", "Click Statements", "Download PDF"] },
      { title: "Regions Mobile", steps: ["Open Regions app", "Tap account", "Select Statements", "Download"] },
    ],
  },
  "huntington-bank": {
    name: "Huntington Bank",
    fullName: "The Huntington National Bank",
    type: "Regional Bank",
    headquarters: "Columbus, OH",
    founded: "1866",
    customers: "7 million+",
    color: "#006F4E",
    statementFormats: ["Huntington Online PDF", "Asterisk-Free Checking Statement", "Business Checking PDF", "Hub Statement"],
    popularFor: ["Midwest small business exports", "Asterisk-Free checking PDF", "Overdraft protection statements"],
    downloadInstructions: [
      { title: "Huntington Online", steps: ["Log in at huntington.com", "Select account", "Click Statements", "Download PDF"] },
      { title: "Huntington Mobile", steps: ["Open Huntington app", "Tap account", "Select Statements", "Download PDF"] },
    ],
  },
  "m-and-t-bank": {
    name: "M&T Bank",
    fullName: "Manufacturers and Traders Trust Company",
    type: "Regional Bank",
    headquarters: "Buffalo, NY",
    founded: "1856",
    customers: "4 million+",
    color: "#00467F",
    statementFormats: ["M&T Online PDF", "MyChoice Checking Statement", "Business Banking PDF", "M&T Credit Card Statement"],
    popularFor: ["Northeast business banking PDF", "MyChoice Premium checking", "QuickBooks-compatible exports"],
    downloadInstructions: [
      { title: "M&T Online Banking", steps: ["Log in at mtb.com", "Select account", "Click Statements", "Download PDF"] },
      { title: "M&T Mobile", steps: ["Open M&T app", "Tap account", "Select Statements", "Download PDF"] },
    ],
  },
  "first-citizens-bank": {
    name: "First Citizens Bank",
    fullName: "First Citizens BancShares, Inc.",
    type: "Regional Bank",
    headquarters: "Raleigh, NC",
    founded: "1898",
    customers: "3 million+",
    color: "#B22222",
    statementFormats: ["First Citizens Online PDF", "Free Checking Statement", "Business Checking PDF", "SVB Account Statement"],
    popularFor: ["Silicon Valley Bank legacy accounts", "Free checking PDF", "Startup banking exports"],
    downloadInstructions: [
      { title: "First Citizens Online", steps: ["Log in at firstcitizens.com", "Select account", "Click Statements", "Download PDF"] },
      { title: "Mobile App", steps: ["Open First Citizens app", "Tap account", "Select Statements", "Download PDF"] },
    ],
  },
  "keybank": {
    name: "KeyBank",
    fullName: "KeyBank National Association",
    type: "Regional Bank",
    headquarters: "Cleveland, OH",
    founded: "1825",
    customers: "4 million+",
    color: "#CC0000",
    statementFormats: ["KeyBank Online PDF", "Key Smart Checking Statement", "Business Checking PDF", "Key2More Rewards Statement"],
    popularFor: ["Key Smart checking exports", "Business payroll statements", "Home equity loan PDF"],
    downloadInstructions: [
      { title: "KeyBank Online", steps: ["Log in at key.com", "Select account", "Click Statements", "Download PDF"] },
      { title: "KeyBank Mobile", steps: ["Open KeyBank app", "Tap account", "Select Statements", "Download"] },
    ],
  },
  "suntrust": {
    name: "SunTrust (Truist)",
    fullName: "SunTrust Bank (now Truist)",
    type: "Regional Bank",
    headquarters: "Atlanta, GA",
    founded: "1891",
    customers: "10 million+",
    color: "#5C068C",
    statementFormats: ["SunTrust Online PDF", "Essential Checking Statement", "Business PDF", "SunTrust Mortgage Statement"],
    popularFor: ["Southeast business exports", "Essential checking PDF", "Mortgage payoff statements"],
    downloadInstructions: [
      { title: "Truist Online (formerly SunTrust)", steps: ["Log in at truist.com", "Select account", "Click Statements", "Download PDF"] },
      { title: "Mobile App", steps: ["Open Truist app", "Tap account", "Tap Statements", "Download PDF"] },
    ],
  },
};
