import React from "react";
import Link from "next/link";
import { Metadata } from "next";
import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";
import {
  ArrowRight,
  Shield,
  FileCheck,
  Zap,
  HelpCircle
} from "lucide-react";

export const metadata: Metadata = {
  title: "Convert Bank Statement to CSV Online Instantly | StatementToExcel",
  description:
    "Convert PDF bank statements to CSV online securely. Extract financial tables dynamically, edit transactions in preview grid, and export cleanly.",
  alternates: {
    canonical: "https://bankstatementtoexcelconverter.com/bank-statement-to-csv",
  },
};

export default function BankStatementToCsvPage() {
  const faqs = [
    {
      q: "How do I convert a bank statement PDF to CSV format?",
      a: "Upload your PDF bank statement file to our online platform. Our positioning engine extracts character blocks, aligns columns dynamically, and renders them in a spreadsheet layout. From there, click 'Export' and choose 'CSV' to download."
    },
    {
      q: "Is CSV format compatible with QuickBooks?",
      a: "Yes, CSV (Comma-Separated Values) files generated by our tool can be directly imported into QuickBooks, Xero, Sage, Wave, or any standard financial ledger software."
    },
    {
      q: "Does this utility support multi-line transactions?",
      a: "Absolutely! The coordinate-based table extraction automatically merges multi-line narratives that wrap onto adjacent rows, keeping them in a single transaction row."
    },
    {
      q: "Can I edit the values before downloading the CSV?",
      a: "Yes, the preview grid behaves exactly like Excel or Google Sheets. Double-click cells to modify values, delete extra header rows, and view selected sum calculations instantly before downloading."
    }
  ];

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": faqs.map(faq => ({
      "@type": "Question",
      "name": faq.q,
      "acceptedAnswer": {
        "@type": "Answer",
        "text": faq.a
      }
    }))
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <Navbar />

      {/* Hero Section */}
      <section className="pt-32 pb-20 px-4 bg-gradient-to-br from-slate-900 via-slate-800 to-slate-950 text-white text-center">
        <div className="max-w-4xl mx-auto">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-primary-950/50 border border-primary-500/30 text-primary-300 text-sm font-semibold mb-6">
            <Zap size={14} /> Quick CSV Compilation & Dynamic Mapping
          </div>
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold tracking-tight mb-6">
            Convert Bank Statement to <span className="text-primary-400">CSV</span>
          </h1>
          <p className="text-lg sm:text-xl text-slate-300 max-w-2xl mx-auto mb-10 leading-relaxed">
            Convert PDF bank statements to structured CSV formats online. Local in-browser parsing ensures absolute data privacy and instant spreadsheet previews.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link href="/app" className="btn-primary px-8 py-4 text-base font-bold shadow-lg shadow-primary-500/20 w-full sm:w-auto">
              Start CSV Conversion <ArrowRight size={18} className="ml-2" />
            </Link>
            <Link href="/pricing" className="btn-secondary px-8 py-4 text-base font-medium text-white border-slate-700 hover:bg-slate-800/50 w-full sm:w-auto">
              View Pricing
            </Link>
          </div>
        </div>
      </section>

      {/* Content Section */}
      <main className="max-w-5xl mx-auto px-4 py-16">
        <article className="prose prose-slate max-w-none lg:prose-lg bg-white p-8 sm:p-12 rounded-3xl border border-slate-200 shadow-sm">
          
          <h2 className="text-3xl font-bold text-slate-900 mb-6">Why Convert Bank Statements to CSV Files?</h2>
          <p className="text-slate-600 leading-relaxed mb-6">
            For bookkeeping operations, database migrations, and financial ledger syncs, the CSV format is the absolute standard. Standard PDF formats prevent easy parsing and matching, making it difficult to automate accounting reports or tax filings. Manual input is slow and prone to errors.
          </p>
          <p className="text-slate-600 leading-relaxed mb-8">
            Our online **Bank Statement to CSV** converter automates this process. Using coordinate-based heuristics, it scans each page to align columns dynamically. It maps all values (like dates, descriptions, checks, debits, credits, and balances) to active rows, letting you edit them online before downloading.
          </p>

          <div className="grid sm:grid-cols-2 md:grid-cols-3 gap-6 my-12">
            <div className="p-6 bg-slate-50 rounded-2xl border border-slate-200">
              <Shield className="text-primary-600 mb-4" size={28} />
              <h3 className="text-lg font-bold text-slate-800 mb-2">Completely Secure</h3>
              <p className="text-sm text-slate-500">Your statements remain private. All character extraction is handled inside secure local contexts.</p>
            </div>
            <div className="p-6 bg-slate-50 rounded-2xl border border-slate-200">
              <Zap className="text-primary-600 mb-4" size={28} />
              <h3 className="text-lg font-bold text-slate-800 mb-2">Position-Driven Parsing</h3>
              <p className="text-sm text-slate-500">Extracts characters based on coordinate systems, preserving structural tables and headers.</p>
            </div>
            <div className="p-6 bg-slate-50 rounded-2xl border border-slate-200">
              <FileCheck className="text-primary-600 mb-4" size={28} />
              <h3 className="text-lg font-bold text-slate-800 mb-2">Editable Grid Preview</h3>
              <p className="text-sm text-slate-500">Preview, edit rows, delete non-transaction notes, and sum selected ranges easily on the preview screen.</p>
            </div>
          </div>

          <h2 className="text-3xl font-bold text-slate-900 mb-6">Instructions for Converting Statements to CSV</h2>
          <ol className="list-decimal pl-6 space-y-4 text-slate-600 mb-10">
            <li>
              <strong>Choose File:</strong> Drag your bank statement PDF to our converter page or select it from your local folders.
            </li>
            <li>
              <strong>Validate Grid:</strong> {"The text blocks are immediately formatted into a grid matching the statement's structure."}
            </li>
            <li>
              <strong>Clean Data:</strong> Double-click cells to adjust values, correct typos, or delete non-transaction notes.
            </li>
            <li>
              <strong>Export CSV:</strong> {"Click the 'Export' button, select 'CSV' and download the formatted data."}
            </li>
          </ol>

          <h2 className="text-3xl font-bold text-slate-900 mb-6">Accurate Multi-Line Row Grouping</h2>
          <p className="text-slate-600 leading-relaxed mb-6">
            A common issue with standard conversion tools is when long narratives wrap across multiple rows in the PDF. This results in empty transaction rows, breaking reconciliation templates. Our coordinate parser looks ahead to group these wrapped blocks into a single description cell.
          </p>

          <h3 className="text-xl font-bold text-slate-800 mb-4">Supported Banks</h3>
          <p className="text-slate-600 leading-relaxed mb-8">
            The platform is brand-agnostic and processes layout grids dynamically. It converts statements from HSBC, Barclays, Chase, Bank of America, Wells Fargo, SBI, HDFC, ICICI, and Axis, without needing custom scripts for each institution.
          </p>

          <hr className="border-slate-200 my-12" />

          {/* FAQs */}
          <h2 className="text-3xl font-bold text-slate-900 mb-8 flex items-center gap-2">
            <HelpCircle className="text-primary-600" /> Frequently Asked Questions
          </h2>
          <div className="space-y-6">
            {faqs.map((faq, i) => (
              <div key={i} className="pb-6 border-b border-slate-100 last:border-0">
                <h4 className="text-lg font-bold text-slate-800 mb-2">{faq.q}</h4>
                <p className="text-slate-600">{faq.a}</p>
              </div>
            ))}
          </div>

          {/* CTA Banner */}
          <div className="mt-16 bg-gradient-to-br from-primary-900 to-primary-950 p-8 sm:p-10 rounded-2xl text-white text-center">
            <h3 className="text-2xl sm:text-3xl font-extrabold mb-4">Convert Your PDF to CSV Online Safely</h3>
            <p className="text-slate-300 max-w-xl mx-auto mb-8 text-sm sm:text-base">
              Try our converter today. Free uploads, instant previews, and easy CSV downloads.
            </p>
            <Link href="/app" className="btn-primary bg-white text-primary-900 hover:bg-slate-100 px-8 py-3 text-sm font-bold shadow-lg">
              Start Free Now
            </Link>
          </div>

        </article>
      </main>

      <Footer />
    </div>
  );
}
